#!/bin/bash

# Mobile App Fix - Server Restart Script
# This script will help you restart both servers with the correct configuration

echo "🔄 Mobile App Network Fix - Server Restart"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: You need to manually stop and restart your servers"
echo ""
echo "📋 STEP 1: Stop Backend Server"
echo "   → Go to the terminal running 'yarn dev' in api-backend-nodejs"
echo "   → Press Ctrl+C to stop it"
echo ""
echo "📋 STEP 2: Stop Frontend Server"
echo "   → Go to the terminal running 'yarn dev' in frontend-nextjs"
echo "   → Press Ctrl+C to stop it"
echo ""
echo "📋 STEP 3: Restart Backend (in api-backend-nodejs terminal)"
echo "   → Run: yarn dev"
echo "   → ✅ Look for: 'Server running on http://0.0.0.0:5001'"
echo "   → ❌ If you see 'localhost:5001' instead, the .env wasn't updated!"
echo ""
echo "📋 STEP 4: Restart Frontend (in frontend-nextjs terminal)"
echo "   → Run: yarn dev"
echo "   → ✅ Look for: 'Network: http://192.168.1.34:3000'"
echo ""
echo "📋 STEP 5: Restart Mobile App (in mobile-capacitor terminal)"
echo "   → Run: yarn run:ios:reload"
echo ""
echo "🎯 Expected Result:"
echo "   - Mobile app loads successfully"
echo "   - Backend logs show: 'GET /api/v1/salons 200 in XXXms'"
echo ""
echo "=========================================="
